const fs=require('fs');
(async()=>{
const tabs=await(await fetch('http://127.0.0.1:9223/json')).json();const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);let id=0;const pending=new Map();ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)(m.result);pending.delete(m.id)}};const send=(method,params={})=>new Promise(r=>{pending.set(++id,r);ws.send(JSON.stringify({id,method,params}))});
await send('Network.enable');await send('Network.setBlockedURLs',{urls:['https://*','http://framer*']});await send('Network.setCacheDisabled',{cacheDisabled:true});
const pages=['index.html','about.html','solutions.html','team.html','references.html','contact.html','blog.html',...fs.readdirSync('team').filter(p=>p.endsWith('.html')).map(p=>'team/'+p),...fs.readdirSync('blog').filter(p=>p.endsWith('.html')).map(p=>'blog/'+p)];const out=[];
for(const width of (process.argv.includes('--all')?[320,390,520,809,1000,1440]:[390]))for(const page of pages){
await send('Emulation.setDeviceMetricsOverride',{width,height:850,deviceScaleFactor:1,mobile:width<810});await send('Page.navigate',{url:'http://127.0.0.1:8765/'+page});await new Promise(r=>setTimeout(r,1000));
const r=await send('Runtime.evaluate',{expression:`(()=>{const rect=e=>{const r=e.getBoundingClientRect();const s=getComputedStyle(e);return {x:r.x,width:r.width,padding:s.paddingLeft}};return {header:document.querySelector('.pse-nav')&&rect(document.querySelector('.pse-nav')),footers:[...document.querySelectorAll('footer')].filter(e=>e.getBoundingClientRect().width).map(e=>({ ...rect(e),parent:rect(e.parentElement)})),viewport:innerWidth,scroll:document.documentElement.scrollWidth}})()`,returnByValue:true});out.push({page,width,...r.result?.value});}
fs.writeFileSync('.visual-check/mobile-width'+(process.argv.includes('--all')?'-after':'-before')+'.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out));ws.close();})().catch(e=>{console.error(e);process.exit(1)});
